---
- name: Delete all objects from an S3 bucket
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Delete objects from S3
      amazon.aws.s3_object:
        bucket: "{{ bucket_name }}"
        mode: delobj
        object: "*"
      register: sync_result
    
    - name: Print sync result
      ansible.builtin.debug:
        msg: "{{ sync_result }}"