---
- name: Sync files with S3
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Sync files with S3
      community.aws.s3_sync:
        bucket: "{{ bucket_name }}"
        ## The path starts from where the playbook is executed
        file_root: "../../app/{{ app_name }}/build"
        include: "*"
        permission: public-read
      register: sync_result

    - name: Print sync result
      ansible.builtin.debug:
        msg: "{{ sync_result }}"
