---
- name: Sync files with S3
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Sync files with S3
      community.aws.s3_sync:
        bucket: "{{ bucket_name }}"
        file_root: "app/{{ app_name }}/build"
        region: "us-east-1"
        permission: public-read
        include: "*"
      register: sync_result

    - name: Print sync result
      debug:
        var: sync_result
