name: Docker

on:
  push:
    branches: [ "master" ]
    paths: [ 
      "docker/*.Dockerfile",
      ".github/workflows/publish.yml",
      ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file docker/es.Dockerfile --tag easy-static:latest

    - name: Publish Docker image to GitHub Packages
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
        docker tag easy-static:latest docker.pkg.github.com/${{ github.repository }}/easy-static:latest
        docker push docker.pkg.github.com/${{ github.repository }}/easy-static:latest
    
      outputs:
        time: ${{ steps.time.outputs.time }}
        build-completed: true