name: Build Docker image and publish to GitHub Packages and run Trivy vulnerability scanner

on:
  push:
    branches: [ "master" ]
    paths: [ 
      "docker/*.Dockerfile",
      ".github/workflows/publish.yml",
      ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file docker/es.Dockerfile --tag easy-static:$(date +%s)
    
    - name: Store image on GitHub Packages
      run: |
        docker tag easy-static:$(date +%s) docker.pkg.github.com/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/easy-static:$(date +%s)
        docker push docker.pkg.github.com/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/easy-static:$(date +%s)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
      with:
        image-ref: docker.pkg.github.com/$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')/easy-static:$(date +%s)
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: trivy-results.sarif